### ISSUE TITLE
conduct load: Unable to contact ConductR.

### ISSUE THREAD

**Issue by pocman** [typesafehub/conductr-cli#171]
Hi, 

I deployed a ConductR cluster using conductr-ansible.
Using `sbt generateInstallationScript`, adding '-i x.x.x.x' and running the generated script, I get :

```
Error: Unable to contact ConductR.
Error: Reason: ('Connection aborted.', timeout('timed out',))
Error: Make sure it can be accessed at http://x.x.x.x:9005/bundles
```

If I run `conduct services -i  x.x.x.x`, I get : 

```
SERVICE       BUNDLE ID  BUNDLE NAME  STATUS
http://:9000  cad6b70    front-end    Running
http://:9000  cad6b70    front-end    Running
http://:9000  cad6b70    front-end    Running
http://:9999  f9069c9    visualizer   Running
http://:9999  f9069c9    visualizer   Running
http://:9999  f9069c9    visualizer   Running
```

It's working fine If I ssh on x.x.x.x to run the `conduct load` command.
However, if I run `conduct services`, I get : 

```
ubuntu@ip-10-0-1-8:~$ conduct services
SERVICE NAME  BUNDLE ID  BUNDLE NAME  STATUS
```

I set the security groups policies as described and I'm able to access `http://x.x.x.x:9005/bundles`.

```
[
   {
      "bundleId":"cad6b7046648999862f8f547d23ccef9",
      "bundleDigest":"cad6b7046648999862f8f547d23ccef999ca73f7bbfe9f2723d04af8ac18c404",
      "attributes":{
         "system":"front-end",
         "nrOfCpus":0.1,
         "memory":402653184,
         "diskSpace":200000000,
         "roles":[
            "web"
         ],
         "bundleName":"front-end"
      },
      "bundleConfig":{
         "endpoints":{
            "web":{
               "bindProtocol":"http",
               "services":[
                  "http://:9000"
               ]
            }
         }
      },
      "bundleScale":3,
      "bundleExecutions":[
         {
            "host":"10.0.2.111",
            "endpoints":{
               "web":{
                  "bindPort":10007,
                  "hostPort":10007
               }
            },
            "isStarted":true
         },
         {
            "host":"10.0.3.132",
            "endpoints":{
               "web":{
                  "bindPort":10007,
                  "hostPort":10007
               }
            },
            "isStarted":true
         },
         {
            "host":"10.0.1.8",
            "endpoints":{
               "web":{
                  "bindPort":10007,
                  "hostPort":10007
               }
            },
            "isStarted":true
         }
      ],
      "bundleInstallations":[
         {
            "uniqueAddress":{
               "address":"akka.tcp://conductr@10.0.2.111:9004",
               "uid":1899259626
            },
            "bundleFile":"file:///tmp/cad6b7046648999862f8f547d23ccef999ca73f7bbfe9f2723d04af8ac18c404.zip"
         },
         {
            "uniqueAddress":{
               "address":"akka.tcp://conductr@10.0.3.132:9004",
               "uid":-1816485582
            },
            "bundleFile":"file:///tmp/cad6b7046648999862f8f547d23ccef999ca73f7bbfe9f2723d04af8ac18c404.zip"
         },
         {
            "uniqueAddress":{
               "address":"akka.tcp://conductr@10.0.1.8:9004",
               "uid":-1105666985
            },
            "bundleFile":"file:///tmp/cad6b7046648999862f8f547d23ccef999ca73f7bbfe9f2723d04af8ac18c404.zip"
         }
      ],
      "hasError":false
   },
   {
      "bundleId":"f9069c9396062c5c571ca0e0da4767f4",
      "bundleDigest":"f9069c9396062c5c571ca0e0da4767f43ea1b725075b7a9073db08326aee708b",
      "attributes":{
         "system":"visualizer",
         "nrOfCpus":1,
         "memory":67108864,
         "diskSpace":35000000,
         "roles":[
            "web"
         ],
         "bundleName":"visualizer"
      },
      "bundleConfig":{
         "endpoints":{
            "web":{
               "bindProtocol":"http",
               "services":[
                  "http://:9999"
               ]
            }
         }
      },
      "bundleScale":3,
      "bundleExecutions":[
         {
            "host":"10.0.1.8",
            "endpoints":{
               "web":{
                  "bindPort":10822,
                  "hostPort":10822
               }
            },
            "isStarted":true
         },
         {
            "host":"10.0.2.111",
            "endpoints":{
               "web":{
                  "bindPort":10822,
                  "hostPort":10822
               }
            },
            "isStarted":true
         },
         {
            "host":"10.0.3.132",
            "endpoints":{
               "web":{
                  "bindPort":10822,
                  "hostPort":10822
               }
            },
            "isStarted":true
         }
      ],
      "bundleInstallations":[
         {
            "uniqueAddress":{
               "address":"akka.tcp://conductr@10.0.1.8:9004",
               "uid":-1105666985
            },
            "bundleFile":"file:///tmp/f9069c9396062c5c571ca0e0da4767f43ea1b725075b7a9073db08326aee708b.zip"
         },
         {
            "uniqueAddress":{
               "address":"akka.tcp://conductr@10.0.2.111:9004",
               "uid":1899259626
            },
            "bundleFile":"file:///tmp/f9069c9396062c5c571ca0e0da4767f43ea1b725075b7a9073db08326aee708b.zip"
         },
         {
            "uniqueAddress":{
               "address":"akka.tcp://conductr@10.0.3.132:9004",
               "uid":-1816485582
            },
            "bundleFile":"file:///tmp/f9069c9396062c5c571ca0e0da4767f43ea1b725075b7a9073db08326aee708b.zip"
         }
      ],
      "hasError":false
   }
]
```

**Comment by huntc** [comment]
The `conduct services` command was badly named. The latest CLI now refers to it as `conduct service-names`. The command will list those services that have service names that can be retrieved via the service locator. 

Does this help?

**Comment by pocman** [comment]
Hi @huntc,
My issue is not related to conduct services but to conduct load from a computer that is not a node of the cluster. 
I'm able to access http://x.x.x.x:9005/bundles from my laptop but I get the following when trying to load a bundle from my laptop :

Error: Unable to contact ConductR.
Error: Reason: ('Connection aborted.', timeout('timed out',))
Error: Make sure it can be accessed at http://x.x.x.x:9005/bundles

**Comment by huntc** [comment]
This is odd. Per chance, did you generate the bundle on Windows? There was a bug in the CLI in relation to Windows that is now fixed in 0.41 of the CLI. Also, perhaps ensure that you're on 1.1.11 of ConductR (recently released).

Are you able to run Wireshark or tcpdump and get a feel for what is happening across the wire?

FYI we use `conduct load` across a WAN quite often, so there's no inherent issue with it.

**Comment by pocman** [comment]
The bundle is generated on my mac but I also used the pre-generated vizualiser bundle.
I updated the cluster to 1.1.11, still the same issue.
My security group is open for 9004, 9005 and 9006.

**Comment by edwardcallahan** [comment]
@pocman, is 9005 open to 0.0.0.0/0 directly in SG or via ELB or ?

I would suggest keeping 9005 private. Ssh tunnel  so that you can access 9005 from your laptop instead. Thus 9005 is not available to the world.

A Bastion host can be nice too. Build your in dev bundle branches on the bastion to avoid WAN i/o.

**Comment by pocman** [comment]
9004, 9005 and 9006 are just opened for our office IP and the SG.
We exposed 9000 and 9999 to the ELB.
Currently, we have to ssh on a node and run `scp *bundle *bundle` and `conduct load ...`.

Didn't saw the `tcpdump` from @huntc, I will try that.
I will try from our ansible node but I'm pretty sure that it will have the same result.

**Comment by edwardcallahan** [comment]
I see. Thanks for the info. 

Summary:
- Both bundles, front-end and visualizer, stream (load) to cluster from cluster - the bundle is ok. The cluster control proto is ok.
- `conduct` commands from office network `info`, `services` work. Control protocol reachable from office net.
- Both bundles do NOT stream from office network to cluster.

Please correct if wrong or add any other differences we know of. Are you using `conduct load` from within sbt, from the console or both?

Thanks for trying `tcpdump`. It does sound like the network given the above.

**Comment by pocman** [comment]
From Office : 

```
Retrieving bundle...
Retrieving file:///Users/poc/workspace/toutatis/user-impl/target/bundle/user-impl-v1-daaf67ed070c2f5c2f0a62dce627794b891211c90d933e6d0c1f8d77a13dabd2.zip
Loading bundle to ConductR...
Error: Unable to contact ConductR.
Error: Reason: ('Connection aborted.', timeout('timed out',))
Error: Make sure it can be accessed at http://x.x.x.x:9005/bundles
```

From Ansible Controller on AWS : 

```
conduct load user-impl-v1-daaf67ed070c2f5c2f0a62dce627794b891211c90d933e6d0c1f8d77a13dabd2.zip -i x.x.x.x -v
Retrieving bundle...
Loading bundle from cache typesafe/bundle/user-impl-v1-daaf67ed070c2f5c2f0a62dce627794b891211c90d933e6d0c1f8d77a13dabd2.zip
Retrieving file:///home/ubuntu/user-impl-v1-daaf67ed070c2f5c2f0a62dce627794b891211c90d933e6d0c1f8d77a13dabd2.zip
Loading bundle to ConductR...
{
  "bundleId": "daaf67ed070c2f5c2f0a62dce627794b",
  "requestId": "8d93833a-d4ec-440c-a651-afac9f1bb71f"
}
Bundle daaf67ed070c2f5c2f0a62dce627794b waiting to be installed
Bundle daaf67ed070c2f5c2f0a62dce627794b installed
Bundle loaded.
Start bundle with: conduct run --ip x.x.x.x daaf67e
Unload bundle with: conduct unload --ip x.x.x.x daaf67e
Print ConductR info with: conduct info --ip x.x.x.x
```

tcpdump for Office : 

```
tcpdump: data link type PKTAP
tcpdump: listening on pktap, link-type PKTAP (Packet Tap), capture size 262144 bytes
09:50:42.675090 IP (tos 0x0, ttl 64, id 14672, offset 0, flags [none], proto TCP (6), length 40)
    poc.50793 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [.], cksum 0x7ba4 (correct), seq 1910226707, ack 922463375, win 4096, length 0
09:50:42.699101 IP (tos 0x0, ttl 42, id 4889, offset 0, flags [DF], proto TCP (6), length 52)
    ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005 > poc.50793: Flags [.], cksum 0x2bb7 (correct), seq 1, ack 1, win 227, options [nop,nop,TS val 86041141 ecr 459285308], length 0
09:51:04.400356 IP (tos 0x0, ttl 42, id 4890, offset 0, flags [DF], proto TCP (6), length 52)
    ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005 > poc.50793: Flags [R.], cksum 0x16b0 (correct), seq 1, ack 1, win 227, options [nop,nop,TS val 86046520 ecr 459285308], length 0
09:51:51.639952 IP (tos 0x0, ttl 64, id 17589, offset 0, flags [DF], proto TCP (6), length 64)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [S], cksum 0x7d2c (correct), seq 4282625562, win 65535, options [mss 1460,nop,wscale 5,nop,nop,TS val 459399457 ecr 0,sackOK,eol], length 0
09:51:51.664561 IP (tos 0x0, ttl 43, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005 > poc.50850: Flags [S.], cksum 0x5613 (correct), seq 3482572007, ack 4282625563, win 26847, options [mss 1460,sackOK,TS val 86058383 ecr 459399457,nop,wscale 7], length 0
09:51:51.664620 IP (tos 0x0, ttl 64, id 27226, offset 0, flags [DF], proto TCP (6), length 52)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [.], cksum 0xdd91 (correct), seq 1, ack 1, win 4117, options [nop,nop,TS val 459399481 ecr 86058383], length 0
09:51:51.664723 IP (tos 0x0, ttl 64, id 3655, offset 0, flags [DF], proto TCP (6), length 308)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [P.], cksum 0x0c18 (correct), seq 1:257, ack 1, win 4117, options [nop,nop,TS val 459399481 ecr 86058383], length 256
09:51:51.664863 IP (tos 0x0, ttl 64, id 345, offset 0, flags [DF], proto TCP (6), length 1500)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [.], cksum 0xdff0 (correct), seq 257:1705, ack 1, win 4117, options [nop,nop,TS val 459399481 ecr 86058383], length 1448
09:51:51.664867 IP (tos 0x0, ttl 64, id 61758, offset 0, flags [DF], proto TCP (6), length 1500)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [.], cksum 0x4970 (correct), seq 1705:3153, ack 1, win 4117, options [nop,nop,TS val 459399481 ecr 86058383], length 1448
09:51:51.688217 IP (tos 0x0, ttl 43, id 61821, offset 0, flags [DF], proto TCP (6), length 52)
    ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005 > poc.50850: Flags [.], cksum 0xebc5 (correct), seq 1, ack 257, win 219, options [nop,nop,TS val 86058389 ecr 459399481], length 0
09:51:51.688255 IP (tos 0x0, ttl 64, id 55931, offset 0, flags [DF], proto TCP (6), length 1500)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [.], cksum 0x817c (correct), seq 3153:4601, ack 1, win 4117, options [nop,nop,TS val 459399504 ecr 86058389], length 1448
09:51:51.689336 IP (tos 0x0, ttl 43, id 61822, offset 0, flags [DF], proto TCP (6), length 52)
    ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005 > poc.50850: Flags [.], cksum 0xe607 (correct), seq 1, ack 1705, win 241, options [nop,nop,TS val 86058389 ecr 459399481], length 0
09:51:51.689339 IP (tos 0x0, ttl 43, id 61823, offset 0, flags [DF], proto TCP (6), length 52)
    ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005 > poc.50850: Flags [.], cksum 0xe048 (correct), seq 1, ack 3153, win 264, options [nop,nop,TS val 86058389 ecr 459399481], length 0
09:51:51.689380 IP (tos 0x0, ttl 64, id 42178, offset 0, flags [DF], proto TCP (6), length 1500)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [.], cksum 0x8264 (correct), seq 4601:6049, ack 1, win 4117, options [nop,nop,TS val 459399505 ecr 86058389], length 1448
09:51:51.689389 IP (tos 0x0, ttl 64, id 9718, offset 0, flags [DF], proto TCP (6), length 1500)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [.], cksum 0x47a9 (correct), seq 6049:7497, ack 1, win 4117, options [nop,nop,TS val 459399505 ecr 86058389], length 1448
09:51:51.689405 IP (tos 0x0, ttl 64, id 21645, offset 0, flags [DF], proto TCP (6), length 1500)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [.], cksum 0x5bfe (correct), seq 7497:8945, ack 1, win 4117, options [nop,nop,TS val 459399505 ecr 86058389], length 1448
09:51:51.689406 IP (tos 0x0, ttl 64, id 30051, offset 0, flags [DF], proto TCP (6), length 1500)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [.], cksum 0xbb09 (correct), seq 8945:10393, ack 1, win 4117, options [nop,nop,TS val 459399505 ecr 86058389], length 1448
09:51:51.712119 IP (tos 0x0, ttl 43, id 61824, offset 0, flags [DF], proto TCP (6), length 52)
    ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005 > poc.50850: Flags [.], cksum 0xda6d (correct), seq 1, ack 4601, win 286, options [nop,nop,TS val 86058395 ecr 459399504], length 0
09:51:51.712171 IP (tos 0x0, ttl 64, id 28103, offset 0, flags [DF], proto TCP (6), length 1500)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [.], cksum 0x5845 (correct), seq 10393:11841, ack 1, win 4117, options [nop,nop,TS val 459399527 ecr 86058395], length 1448
09:51:51.712178 IP (tos 0x0, ttl 64, id 9623, offset 0, flags [DF], proto TCP (6), length 1500)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [.], cksum 0xaade (correct), seq 11841:13289, ack 1, win 4117, options [nop,nop,TS val 459399527 ecr 86058395], length 1448
09:51:51.714246 IP (tos 0x0, ttl 43, id 61825, offset 0, flags [DF], proto TCP (6), length 52)
    ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005 > poc.50850: Flags [.], cksum 0xd4ad (correct), seq 1, ack 6049, win 309, options [nop,nop,TS val 86058395 ecr 459399505], length 0
09:51:51.714250 IP (tos 0x0, ttl 43, id 61826, offset 0, flags [DF], proto TCP (6), length 52)
    ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005 > poc.50850: Flags [.], cksum 0xceee (correct), seq 1, ack 7497, win 332, options [nop,nop,TS val 86058395 ecr 459399505], length 0
09:51:51.714251 IP (tos 0x0, ttl 43, id 61827, offset 0, flags [DF], proto TCP (6), length 52)
    ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005 > poc.50850: Flags [.], cksum 0xc930 (correct), seq 1, ack 8945, win 354, options [nop,nop,TS val 86058395 ecr 459399505], length 0
09:51:51.714253 IP (tos 0x0, ttl 43, id 61828, offset 0, flags [DF], proto TCP (6), length 52)
    ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005 > poc.50850: Flags [.], cksum 0xc371 (correct), seq 1, ack 10393, win 377, options [nop,nop,TS val 86058395 ecr 459399505], length 0
09:51:51.714295 IP (tos 0x0, ttl 64, id 36037, offset 0, flags [DF], proto TCP (6), length 1500)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [.], cksum 0xf0d1 (correct), seq 13289:14737, ack 1, win 4117, options [nop,nop,TS val 459399529 ecr 86058395], length 1448
09:51:51.714302 IP (tos 0x0, ttl 64, id 58953, offset 0, flags [DF], proto TCP (6), length 1500)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [.], cksum 0x860e (correct), seq 14737:16185, ack 1, win 4117, options [nop,nop,TS val 459399529 ecr 86058395], length 1448
09:51:51.714315 IP (tos 0x0, ttl 64, id 5470, offset 0, flags [DF], proto TCP (6), length 1500)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [.], cksum 0x5770 (correct), seq 16185:17633, ack 1, win 4117, options [nop,nop,TS val 459399529 ecr 86058395], length 1448
09:51:51.714316 IP (tos 0x0, ttl 64, id 51122, offset 0, flags [DF], proto TCP (6), length 1500)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [.], cksum 0x115e (correct), seq 17633:19081, ack 1, win 4117, options [nop,nop,TS val 459399529 ecr 86058395], length 1448
09:51:51.714326 IP (tos 0x0, ttl 64, id 26715, offset 0, flags [DF], proto TCP (6), length 1500)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [.], cksum 0xc1ac (correct), seq 19081:20529, ack 1, win 4117, options [nop,nop,TS val 459399529 ecr 86058395], length 1448
09:51:51.714328 IP (tos 0x0, ttl 64, id 5210, offset 0, flags [DF], proto TCP (6), length 1500)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [.], cksum 0xa518 (correct), seq 20529:21977, ack 1, win 4117, options [nop,nop,TS val 459399529 ecr 86058395], length 1448
09:51:51.714336 IP (tos 0x0, ttl 64, id 1832, offset 0, flags [DF], proto TCP (6), length 1500)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [.], cksum 0x517f (correct), seq 21977:23425, ack 1, win 4117, options [nop,nop,TS val 459399529 ecr 86058395], length 1448
09:51:51.714337 IP (tos 0x0, ttl 64, id 11567, offset 0, flags [DF], proto TCP (6), length 1500)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [.], cksum 0x3ede (correct), seq 23425:24873, ack 1, win 4117, options [nop,nop,TS val 459399529 ecr 86058395], length 1448
09:51:51.736274 IP (tos 0x0, ttl 43, id 61829, offset 0, flags [DF], proto TCP (6), length 52)
    ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005 > poc.50850: Flags [.], cksum 0xbd96 (correct), seq 1, ack 11841, win 400, options [nop,nop,TS val 86058401 ecr 459399527], length 0
09:51:51.736277 IP (tos 0x0, ttl 43, id 61830, offset 0, flags [DF], proto TCP (6), length 52)
    ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005 > poc.50850: Flags [.], cksum 0xb7d8 (correct), seq 1, ack 13289, win 422, options [nop,nop,TS val 86058401 ecr 459399527], length 0
09:51:51.736319 IP (tos 0x0, ttl 64, id 9727, offset 0, flags [DF], proto TCP (6), length 1500)
...
09:52:22.097763 IP (tos 0x0, ttl 64, id 57878, offset 0, flags [DF], proto TCP (6), length 52)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [.], cksum 0x9064 (correct), seq 27377354, ack 1, win 4117, options [nop,nop,TS val 459427908 ecr 86065991], length 0
09:52:22.098868 IP (tos 0x0, ttl 43, id 5405, offset 0, flags [DF], proto TCP (6), length 370)
    ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005 > poc.50850: Flags [P.], cksum 0x3e36 (correct), seq 1:319, ack 27377354, win 6039, options [nop,nop,TS val 86065992 ecr 459427877], length 318
09:52:22.098872 IP (tos 0x0, ttl 43, id 5406, offset 0, flags [DF], proto TCP (6), length 52)
    ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005 > poc.50850: Flags [F.], cksum 0x87c1 (correct), seq 319, ack 27377354, win 6039, options [nop,nop,TS val 86065992 ecr 459427877], length 0
09:52:22.098934 IP (tos 0x0, ttl 64, id 59296, offset 0, flags [DF], proto TCP (6), length 40)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [R], cksum 0x3228 (correct), seq 15035620, win 0, length 0
09:52:22.098947 IP (tos 0x0, ttl 64, id 10155, offset 0, flags [DF], proto TCP (6), length 40)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [R], cksum 0x3228 (correct), seq 15035620, win 0, length 0
09:52:22.110773 IP (tos 0x0, ttl 43, id 5407, offset 0, flags [DF], proto TCP (6), length 64)
    ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005 > poc.50850: Flags [.], cksum 0x7601 (correct), seq 320, ack 27377354, win 6039, options [nop,nop,TS val 86065994 ecr 459427898,nop,nop,sack 1 {27377353:27377354}], length 0
09:52:22.110776 IP (tos 0x0, ttl 43, id 5408, offset 0, flags [DF], proto TCP (6), length 64)
    ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005 > poc.50850: Flags [.], cksum 0x7600 (correct), seq 320, ack 27377354, win 6039, options [nop,nop,TS val 86065995 ecr 459427898,nop,nop,sack 1 {27377353:27377354}], length 0
09:52:22.110810 IP (tos 0x0, ttl 64, id 13257, offset 0, flags [DF], proto TCP (6), length 40)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [R], cksum 0x3228 (correct), seq 15035620, win 0, length 0
09:52:22.110830 IP (tos 0x0, ttl 64, id 13347, offset 0, flags [DF], proto TCP (6), length 40)
    poc.50850 > ec2-x-x-x-x.eu-west-1.compute.amazonaws.com.9005: Flags [R], cksum 0x3228 (correct), seq 15035620, win 0, length 0
```

**Comment by corruptmemory** [comment]
@pocman perhaps this has already been tried, but from the output of `conduct service-names -h`

```
  -i IP, --ip IP        The optional ConductR IP, defaults to one of the value
                        in this order:$CONDUCTR_IP orIP address of the docker
                        VM or`127.0.0.1`
```

So question/suggestions:
1. have you tried `conduct services -i x.x.x.x` on the machine you sshed to? Perhaps ConductR is not listening on 127.0.0.1.
2. It may be useful to add `export CONDUCTR_IP="x.x.x.x"` to the `.bashrc` on your boxes so you can connect automatically.

See if any of those things work.

**Comment by pocman** [comment]
Hi,
as mentioned in my previous comment, the bundle loading is working from my ansible controller (with the same access rights as our office network).
This is probably a network speed issue which lead to a time out.

You might want to change your error message ;)

**Comment by markusjura** [comment]
@pocman In the meantime, we have changed the `conduct load` command: https://github.com/typesafehub/conductr-cli/pull/184

Now it does not times out anymore. Instead, a loading bar indicates the current downloading progress.

This PR will be part of the next conductr-cli version.

**Comment by huntc** [comment]
@pocman The new CLI is released (0.43). This should fix the issue. Thanks.
